export const TYPES = {
  LOAD_CUSTOMER: 'LOAD_CUSTOMER',
  LOAD_CUSTOMER_REQUEST: 'LOAD_CUSTOMERS_REQUEST',
  LOAD_CUSTOMER_ERROR: 'LOAD_CUSTOMERS_ERROR',
  LOAD_CUSTOMER_SUCCESS: 'LOAD_CUSTOMERS_SUCCESS',
};
