export const en = {
  common: {
    loading: 'Loading',
    connectionError: 'Connection error',
  },
  home: {
    header: 'Home',
    message: 'Welcome',
    variant: 'App variant: ',
  },
  login: {
    username: 'Email',
    usernameHint: 'Enter your email',
    button: 'Login',
    password: 'Password',
    passwordHint: 'Enter your password',
    invalidCredentials: 'Invalid credentials',
  },
  profile: {
    header: 'Profile',
    logout: 'Logout',
    message: 'This screen has the iOS native large header.',
  },
  ticket: {
    inputFieldHint: 'New ticket form field',
    customerName: 'Customer Name',
    warehouse: 'warehouse',
    date: 'Date',
    partNumber: 'Part Number',
    lotNumber: 'Lot Number',
    surgeon: 'Surgeon',
    poNumber: 'PO Number',
    buttonReview: 'Review Submission',
    buttonSubmit: 'Submit Ticket',
    buttonSuccess: 'Done',
    buttonPending: 'View Pending Ticket',
    buttonFailure: 'Try Again',
    apiError: 'There was an issue with the ticket submission',
    textAddPhotos: 'Add photo(s) - optional',
    textCamera: 'Camera',
    textLibrary: 'Library',
    ticketStatusSucess: 'Your usage Ticket has been successfully submitted.',
    ticketStatusPending:
      'You are currently not connected to the internet. Once you regain access to your network you will have to manually submit this usage ticket.',
    ticketStatusFaliure: 'Submission failed. Please try submitting the ticket again.',
  },
  customer: {
    customers: 'Customers',
  },
};
