export const en = {
  common: {
    loading: 'Loading',
    connectionError: 'Connection error',
  },
  home: {
    header: 'Home',
    message: 'Welcome',
    variant: 'App variant: ',
  },
  login: {
    username: 'Email',
    usernameHint: 'Enter your email',
    button: 'Login',
    password: 'Password',
    passwordHint: 'Enter your password',
    invalidCredentials: 'Invalid credentials',
    somethingIsWrong: 'Something went wrong, please try again',
  },
  profile: {
    header: 'Profile',
    logout: 'Logout',
    message:
      'If you’re having any trouble with the app or require any further information, please reach out to our support team:',
    customerCareEmailAddress: 'customerservice@razormi.com',
    customerCarePhoneNumber: '(123) 456 7890',
    labelPhoneNumber: 'Phone Number',
    labelEmail: 'Email',
    labelAffiliation: 'OEM Affiliation',
  },
  ticket: {
    inputFieldHint: 'New ticket form field',
    customerName: 'Customer Name',
    warehouse: 'warehouse',
    date: 'Date',
    partNumber: 'Part Number',
    lotNumber: 'Lot Number',
    surgeon: 'Surgeon',
    poNumber: 'PO Number',
    buttonReview: 'Review Submission',
    buttonSubmit: 'Submit Ticket',
    buttonSuccess: 'Done',
    buttonPending: 'View Pending Ticket',
    buttonFailure: 'Try Again',
    apiError: 'There was an issue with the ticket submission',
    textAddPhotos: 'Add photo(s) - optional',
    textCamera: 'Camera',
    textLibrary: 'Library',
    ticketStatusSucess: 'Your usage Ticket has been successfully submitted.',
    ticketStatusPending:
      'You are currently not connected to the internet. Once you regain access to your network you will have to manually submit this usage ticket.',
    ticketStatusFaliure: 'Submission failed. Please try submitting the ticket again.',
    ticketFetchFailure: 'There was an issue fetching for tickets',
  },
  customer: {
    customers: 'Customers',
  },
};
